import numpy as np
import Basic as Bsc
import RF_Operators as RF_Op
import Encryption as Enc

"""
Instruction:
  ADTM.py - Adversary deterministic Turning Machine. It prepares plaintext sets; create the corresponding hash tables; sieving the possible keys and recover the picoCrypton master key in chosen plaintext scenario.
  Also, in the aforementioned scenario, it reads the ciphertexts generated by ODTM (Oracle deterministic Turing machine), and checks which kes can satisy the 4-round impossible-differential property.
"""

###################################################################################################
####                     Writing the required plaintexts into a text file                      ####
###################################################################################################
def WriteDoc(ptxList: list, Address: str) -> None:
    try:
        if type(ptxList) != list:
            raise TypeError("The first input must be a list of plaintexts.")
        else:
            Address = Address + "\\Plaintexts.txt"
            Len = len(ptxList)
            flag = True
            with open(Address, "w") as f:
                for i in range(0, Len):
                    f.write("0x")
                    for j in range(0, 4):
                        num = 8 * ptxList[i][j][0] + 4 * ptxList[i][j][1] + 2 * ptxList[i][j][2] + ptxList[i][j][3]
                        f.write(Bsc.Int2Hex(num))
                    f.write("\n")
                    y = round((i + 1) / Len * 100, 2)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"ADTM: {round(y)}% of the writing has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            f.close()

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                    Reading blocks from the text file prepared by ODTM                     ####
###################################################################################################
def ReadDoc(Address: str) -> list:
    try:
        if type(Address) != str:
            raise TypeError("Input must be the address of the target file.")
        else:
            ctxList = []
            Address = Address + "\\Ciphertexts.txt"
            with open(Address, "r") as f:
                Data = f.read()
                f.close()
            Len = len(Data)
            ctr = 0
            ctr2 = 0
            flag = True
            while(ctr < Len):
                if Data[ctr] == "0" and Data[ctr + 1] == "x":
                    ctr += 2
                elif Data[ctr - 2] == "0" and Data[ctr - 1] == "x":
                    ctr3 = 0
                    X = np.array([
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0]
                        ], dtype = np.uint8)
                    for i in range(0, 4):
                        num = Bsc.Hex2Int(Data[ctr + ctr3])
                        B = Bsc.Int2Nib(num)
                        X[i, :] = B.copy()
                        ctr3 += 1
                    ctr += 4
                    ctxList.append(X.copy())
                elif Data[ctr] == "\n":
                    ctr += 1
                    ctr2 += 1
                else:
                    ctr += 1
                y = round(100 * ctr / Len, 2)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"ADTM: {round(y)}% of the reading has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue
            return ctxList

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                            Precomputation process (1st Phase)                             ####
###################################################################################################
def PreComp1() -> list:
    hashList = []
    table = []
    for i in range(0, 256):
        hashList.append(table.copy())
    Z1 = np.array([[0, 0],
                   [0, 0],
                   [0, 0],
                   [0, 0]], dtype = np.uint8)
    W1 = np.array([[0, 0],
                   [0, 0],
                   [0, 0],
                   [0, 0]], dtype = np.uint8)
    X1 = np.array([[0, 0],
                   [0, 0],
                   [0, 0],
                   [0, 0]], dtype = np.uint8)
    Z2 = Z1.copy()
    W2 = W1.copy()
    X2 = X1.copy()
    for i in range(0, 16):
        B = Bsc.Int2Nib(np.uint8(i))
        Z1[0][0] = B[0]
        Z1[0][1] = B[1]
        Z1[1][0] = B[2]
        Z1[1][1] = B[3]
        for j in range(0, 15):
            B = Bsc.Int2Nib(np.uint8(j))
            Z1[2][1] = B[1]
            Z1[3][0] = B[2]
            Z1[3][1] = B[3]
            W1[0][0] = np.uint8(Z1[1][0] ^ Z1[2][0] ^ Z1[3][0])
            W1[1][0] = np.uint8(Z1[0][0] ^ Z1[1][0] ^ Z1[2][0])
            W1[2][0] = np.uint8(Z1[0][0] ^ Z1[1][0] ^ Z1[3][0])
            W1[3][0] = np.uint8(Z1[0][0] ^ Z1[2][0] ^ Z1[3][0])
            W1[0][1] = np.uint8(Z1[0][1] ^ Z1[1][1] ^ Z1[2][1])
            W1[1][1] = np.uint8(Z1[0][1] ^ Z1[1][1] ^ Z1[3][1])
            W1[2][1] = np.uint8(Z1[0][1] ^ Z1[2][1] ^ Z1[3][1])
            W1[3][1] = np.uint8(Z1[1][1] ^ Z1[2][1] ^ Z1[3][1])
            for l in range(j + 1, 16):
                Z2 = Z1.copy()
                B = Bsc.Int2Nib(np.uint8(l))
                Z2[2][0] = B[0]
                Z2[2][1] = B[1]
                Z2[3][0] = B[2]
                Z2[3][1] = B[3]
                W2[0][0] = np.uint8(Z2[1][0] ^ Z2[2][0] ^ Z2[3][0])
                W2[1][0] = np.uint8(Z2[0][0] ^ Z2[1][0] ^ Z2[2][0])
                W2[2][0] = np.uint8(Z2[0][0] ^ Z2[1][0] ^ Z2[3][0])
                W2[3][0] = np.uint8(Z2[0][0] ^ Z2[2][0] ^ Z2[3][0])
                W2[0][1] = np.uint8(Z2[0][1] ^ Z2[1][1] ^ Z2[2][1])
                W2[1][1] = np.uint8(Z2[0][1] ^ Z2[1][1] ^ Z2[3][1])
                W2[2][1] = np.uint8(Z2[0][1] ^ Z2[2][1] ^ Z2[3][1])
                W2[3][1] = np.uint8(Z2[1][1] ^ Z2[2][1] ^ Z2[3][1])
                inNum11 = W1[0][0] * 8 + W1[0][1] * 4 + W1[1][0] * 2 + W1[1][1]
                inNum12 = W1[2][0] * 8 + W1[2][1] * 4 + W1[3][0] * 2 + W1[3][1]
                inNum21 = W2[0][0] * 8 + W2[0][1] * 4 + W2[1][0] * 2 + W2[1][1]
                inNum22 = W2[2][0] * 8 + W2[2][1] * 4 + W2[3][0] * 2 + W2[3][1]
                num1 = 2
                num2 = 0
                outNum11 = RF_Op.SBOX(inNum11, num1)
                outNum12 = RF_Op.SBOX(inNum12, num2)
                outNum21 = RF_Op.SBOX(inNum21, num1)
                outNum22 = RF_Op.SBOX(inNum22, num2)
                B = Bsc.Int2Nib(np.uint8(outNum11))
                X1[0][0] = B[0]
                X1[0][1] = B[1]
                X1[1][0] = B[2]
                X1[1][1] = B[3]
                B = Bsc.Int2Nib(np.uint8(outNum12))
                X1[2][0] = B[0]
                X1[2][1] = B[1]
                X1[3][0] = B[2]
                X1[3][1] = B[3]
                B = Bsc.Int2Nib(np.uint8(outNum21))
                X2[0][0] = B[0]
                X2[0][1] = B[1]
                X2[1][0] = B[2]
                X2[1][1] = B[3]
                B = Bsc.Int2Nib(np.uint8(outNum22))
                X2[2][0] = B[0]
                X2[2][1] = B[1]
                X2[3][0] = B[2]
                X2[3][1] = B[3]
                Delta = np.uint8(X1 ^ X2)
                d1 = Delta[0][0] * 8 + Delta[0][1] * 4 + Delta[1][0] * 2 + Delta[1][1]
                d2 = Delta[2][0] * 8 + Delta[2][1] * 4 + Delta[3][0] * 2 + Delta[3][1]
                num = d1 * 16 + d2
                hashList[num].append(Z1.copy())
                hashList[num].append(Z2.copy())
                hashList[num].append(X1.copy())
                hashList[num].append(X2.copy())
    print("ADTM: The first Pre-computation phase has been completed.")
    return hashList

###################################################################################################
####                            Precomputation process (2nd Phase)                             ####
###################################################################################################
def PreComp2() -> list:
    hashList = []
    table = []
    for i in range(0, 16):
        hashList.append(table.copy())
    S1 = np.array([[0, 0],
                   [0, 0]], dtype = np.uint8)
    V1 = np.array([[0, 0],
                   [0, 0]], dtype = np.uint8)
    V2 = V1.copy()
    for i in range(0, 4):
        S1[1][0] = np.uint8(i % 2)
        S1[0][0] = np.uint8((i - S1[0][1]) // 2)
        for j in range(0, 2):
            S1[1][1] = np.uint8(j % 2)
            S2 = S1.copy()
            S2[0][1] = np.uint8(1 - S1[0][1])
            S2[1][1] = np.uint8(1 - S1[1][1])
            inNum1 = S1[0][0] * 8 + S1[0][1] * 4 + S1[1][0] * 2 + S1[1][1]
            inNum2 = S2[0][0] * 8 + S2[0][1] * 4 + S2[1][0] * 2 + S2[1][1]
            num = 3
            outNum1 = RF_Op.SBOX(inNum1, num)
            outNum2 = RF_Op.SBOX(inNum2, num)
            B = Bsc.Int2Nib(np.uint8(outNum1))
            V1[0][0] = B[0]
            V1[0][1] = B[1]
            V1[1][0] = B[2]
            V1[1][1] = B[3]
            B = Bsc.Int2Nib(np.uint8(outNum2))
            V2[0][0] = B[0]
            V2[0][1] = B[1]
            V2[1][0] = B[2]
            V2[1][1] = B[3]
            Delta = np.uint8(V1 ^ V2)
            d = Delta[0][0] * 8 + Delta[0][1] * 4 + Delta[1][0] * 2 + Delta[1][1]
            hashList[d].append(V1.copy())
            hashList[d].append(V2.copy())
    print("ADTM: The second Pre-computation phase has been completed.")
    return hashList


###################################################################################################
####                                      Data Collection                                      ####
###################################################################################################
def ADTM_Generate(Address: str) -> None:
    try:
        if type(Address) != str:
            raise TypeError("The first input must be a valid address and the second input must be a list.")
        else:
            ptxList = []
            P = np.array([
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0]
                ], dtype = np.uint8)
            for j in range(0, 16):
                B = Bsc.Int2Nib(np.uint8(j))
                P[2][2] = B[0]
                P[2][3] = B[1]
                P[3][2] = B[2]
                P[3][3] = B[3]
                for l in range (0, 256):
                    mod1 = np.uint8(l % 16)
                    div1 = np.uint8((l - mod1) // 16)
                    B1 = Bsc.Int2Nib(mod1)
                    B2 = Bsc.Int2Nib(div1)
                    P[0][0] = B2[0]
                    P[0][1] = B2[1]
                    P[1][0] = B2[2]
                    P[1][1] = B2[3]
                    P[2][0] = B1[0]
                    P[2][1] = B1[1]
                    P[3][0] = B1[2]
                    P[3][1] = B1[3]
                    ptxList.append(P.copy())
                    flag = True
                    y = round(100 * (256 * j + l) / 4096, 3)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"ADTM: {y}% of the generating plaintext pairs has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            WriteDoc(ptxList, Address)

    except ValueError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                              Partial Encrption (1st Phase)                                ####
###################################################################################################
def ADTM_PartEnc1(Address: str, hashTable: list, ctxList: list) -> list:
    try:
        if type(Address) != str or type(hashTable) != list or type(ctxList) != list:
            raise TypeError("The first input must be a valid address and the second and third inputs must be valid lists.")
        else:
            C1 = np.array([
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0]
                ], dtype = np.uint8)
            C2 = np.array([
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0],
                [0, 0, 0, 0]
                ], dtype = np.uint8)
            Len = len(ctxList)
            sievedIndexList = []
            if Len % 256 != 0:
                raise TypeError("There are not enough ciphertexts in the ciphertext's list.")
            else:
                M = Len // 256
                for i in range(0, M):
                    for j in range (0, 255):
                        mod1 = np.uint8(j % 16)
                        div1 = np.uint8((j - mod1) // 16)
                        B1 = Bsc.Int2Nib(mod1)
                        B2 = Bsc.Int2Nib(div1)
                        num0 = 256 * i + j
                        C1 = ctxList[num0]
                        for l in range (j + 1, 256):
                            mod2 = np.uint8(l % 16)
                            div2 = np.uint8((l - mod2) // 16)
                            B3 = Bsc.Int2Nib(mod2)
                            B4 = Bsc.Int2Nib(div2)
                            num1 = 8 * np.uint8(B1[0] ^ B3[0]) + 4 * np.uint8(B1[1] ^ B3[1]) + 2 * np.uint8(B1[2] ^ B3[2]) + np.uint8(B1[3] ^ B3[3])
                            num2 = 8 * np.uint8(B2[0] ^ B4[0]) + 4 * np.uint8(B2[1] ^ B4[1]) + 2 * np.uint8(B2[2] ^ B4[2]) + np.uint8(B2[3] ^ B4[3])
                            num3 = num2 * 16 + num1
                            if len(hashTable[num3]) != 0:
                                num4 = 256 * i + l
                                C2 = ctxList[num4]
                                deltaC = C1 ^ C2
                                w0 = sum(deltaC[:, 0])
                                w1 = sum(deltaC[:, 1])
                                w2 = sum(deltaC[:, 2])
                                if w0 + w1 + w2 == 0:
                                    sievedIndexList.append(num0)
                                    sievedIndexList.append(num4)
                                    sievedIndexList.append(num3)
                        flag = True
                        y = round(100 * (256 * i + j) / (M * 256), 3)
                        if abs(y - round(y)) < 0.05 and flag == True:
                            print(f"ADTM: {y}% of the first phase of partial encryption has been completed.")
                            flag = False
                        elif abs(y - round(y)) >= 0.05:
                            flag = True
                        else:
                            continue
            return sievedIndexList

    except ValueError as e:
        print("Error: Invalid inputs.", e)

###################################################################################################
####                              Partial Encrption (2nd Phase)                                ####
###################################################################################################
def ADTM_PartEnc2(IndexList: list, hashTable1: list, hashTable2: list) -> list:
    try:
        if type(IndexList) != list or type(hashTable1) != list or type(hashTable2) != list:
            raise TypeError("The first input must be a valid address and the second and third inputs must be valid lists.")
        else:
            Len = len(IndexList)
            if Len % 3 != 0:
                raise TypeError("At least one of the input Lists is not valid.")
            else:
                Len //= 3
                updatedSievedList = []
                Y1 = np.array([[0, 0],
                               [0, 0]], dtype = np.uint8)
                Y2 = Y1.copy()
                Ptx = np.array([[0, 0],
                                [0, 0],
                                [0, 0],
                                [0, 0]], dtype = np.uint8)
                keyArray11 = np.array([[0, 0],
                                       [0, 0],
                                       [0, 0],
                                       [0, 0]], dtype = np.uint8)
                keyArray21 = np.array([[0, 0],
                                       [0, 0]], dtype = np.uint8)
                keyArray12 = keyArray11.copy()
                keyArray22 = keyArray21.copy()
                for i in range(0, Len):
                    num1 = IndexList[3 * i] % 256
                    num3 = IndexList[3 * i + 2]
                    mod1 = np.uint8(num1 % 16)
                    div1 = np.uint8((num1 - mod1) // 16)
                    B1 = Bsc.Int2Nib(div1)
                    B2 = Bsc.Int2Nib(mod1)
                    Ptx[0][0] = B1[0]
                    Ptx[0][1] = B1[1]
                    Ptx[1][0] = B1[2]
                    Ptx[1][1] = B1[3]
                    Ptx[2][0] = B2[0]
                    Ptx[2][1] = B2[1]
                    Ptx[3][0] = B2[2]
                    Ptx[3][1] = B2[3]
                    for j in range(0, len(hashTable1[num3]), 4):
                        Z1 = hashTable1[num3][j].copy()
                        Z2 = hashTable1[num3][j + 1].copy()
                        X1 = hashTable1[num3][j + 2].copy()
                        X2 = hashTable1[num3][j + 3].copy()
                        keyArray11 = np.uint8(X1 ^ Ptx)
                        key11Part1 = keyArray11[0][0] * 8 + keyArray11[0][1] * 4 + keyArray11[1][0] * 2 + keyArray11[1][1]
                        key11Part2 = keyArray11[2][0] * 8 + keyArray11[2][1] * 4 + keyArray11[3][0] * 2 + keyArray11[3][1]
                        key11 = int(key11Part1 * 16 + key11Part2)
                        keyArray12 = np.uint8(X2 ^ Ptx)
                        key12Part1 = keyArray12[0][0] * 8 + keyArray12[0][1] * 4 + keyArray12[1][0] * 2 + keyArray12[1][1]
                        key12Part2 = keyArray12[2][0] * 8 + keyArray12[2][1] * 4 + keyArray12[3][0] * 2 + keyArray12[3][1]
                        key12 = int(key12Part1 * 16 + key12Part2)
                        Y1[0][0] = Z1[2][0]
                        Y1[0][1] = Z1[3][0]
                        Y1[1][0] = Z1[2][1]
                        Y1[1][1] = Z1[3][1]
                        Y2[0][0] = Z2[2][0]
                        Y2[0][1] = Z2[3][0]
                        Y2[1][0] = Z2[2][1]
                        Y2[1][1] = Z2[3][1]
                        deltaY = np.uint8(Y1 ^ Y2)
                        num4 = deltaY[0][0] * 8 + deltaY[0][1] * 4 + deltaY[1][0] * 2 + deltaY[1][1]
                        if len(hashTable2[num4]) != 0:
                            for l in range(0, len(hashTable2[num4]), 2):
                                V1 = hashTable2[num4][l].copy()
                                V2 = hashTable2[num4][l + 1].copy()
                                keyArray21 = np.uint8(Y1 ^ V1)
                                key21 = int(keyArray21[0][0] * 8 + keyArray21[0][1] * 4 + keyArray21[1][0] * 2 + keyArray21[1][1])
                                keyArray22 = np.uint8(Y1 ^ V2)
                                key22 = int(keyArray22[0][0] * 8 + keyArray22[0][1] * 4 + keyArray22[1][0] * 2 + keyArray22[1][1])
                                updatedSievedList.append(IndexList[3 * i])
                                updatedSievedList.append(IndexList[3 * i + 1])
                                updatedSievedList.append(key11)
                                updatedSievedList.append(key12)
                                updatedSievedList.append(key21)
                                updatedSievedList.append(key22)
                    flag = True
                    y = round(100 * i / Len, 3)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"ADTM: {y}% of the second phase of partial encryption has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            return updatedSievedList

    except ValueError as e:
        print("Error: Invalid inputs.", e)

###################################################################################################
####                                    Partial Decryption                                     ####
###################################################################################################
def ADTM_PartDec(ctxList: list, sievedIndex: list) -> list:
    try:
        if type(ctxList) != list or type(sievedIndex) != list:
            raise TypeError("Inputs must be valid lists.")
        else:
            Len = len(sievedIndex)
            if Len % 6 != 0:
                raise TypeError("The updated sieved list of keys is not valid.")
            else:
                Len //= 6
                keyList = []
                bl = True
                for i in range(0, 65536):
                    keyList.append(bl)
                vec1 = np.array([[0, 0, 0, 0],
                                 [0, 0, 0, 0]], dtype = np.uint8)
                vec2 = vec1.copy()
                keyVec = vec1.copy()
                T1 = vec1.copy()
                T2 = vec1.copy()
                MK = np.array([[0, 0, 0, 0],
                               [0, 0, 0, 0],
                               [0, 0, 0, 0],
                               [0, 0, 0, 0]], dtype = np.uint8)
                for i in range(0, Len):
                    C1 = ctxList[sievedIndex[6 * i]]
                    C2 = ctxList[sievedIndex[6 * i + 1]]
                    CT1 = RF_Op.Tau(C1)
                    CT2 = RF_Op.Tau(C2)
                    vec1[0, :] = CT1[2, :]
                    vec1[1, :] = CT1[3, :]
                    vec2[0, :] = CT2[2, :]
                    vec2[1, :] = CT2[3, :]
                    for j in range(0, 2):
                        num1 = sievedIndex[6 * i + 2 + j]
                        mod1 = num1 % 16
                        div1 = (num1 - mod1) // 16
                        B1 = Bsc.Int2Nib(np.uint8(div1))
                        B2 = Bsc.Int2Nib(np.uint8(mod1))
                        MK[0][0] = B2[2]
                        MK[0][1] = B2[3]
                        MK[1][0] = B2[2] ^ B1[0]
                        MK[1][1] = B1[1]
                        MK[2][0] = B1[2]
                        MK[2][1] = B2[3] ^ B1[3]
                        MK[3][0] = B2[0]
                        MK[3][1] = B2[1]
                        for l in range(0, 2):
                            num2 = sievedIndex[6 * i + 4 + l]
                            B3 = Bsc.Int2Nib(np.uint8(num2))
                            MK[2][2] = B3[0]
                            MK[2][3] = B3[1]
                            MK[3][2] = B3[2]
                            MK[3][3] = B3[3]
                            keyVec[0][2] = MK[2][0] ^ MK[2][1] ^ MK[2][3] ^ MK[3][3]
                            keyVec[0][3] = MK[3][1] ^ MK[3][2] ^ MK[3][3]
                            keyVec[1][2] = MK[2][0] ^ MK[2][2] ^ MK[2][3] ^ MK[3][3]
                            keyVec[1][3] = MK[2][1] ^ MK[3][0] ^ MK[3][1] ^ MK[3][2]
                            for k in range(0, 16):
                                B4 = Bsc.Int2Nib(np.uint8(k))
                                MK[0][2] = B4[0]
                                MK[0][3] = B4[1]
                                MK[1][2] = B4[2]
                                MK[1][3] = B4[3]
                                keyVec[0][0] = MK[0][1] ^ MK[0][2] ^ MK[0][3] ^ MK[3][1]
                                keyVec[0][1] = MK[1][0] ^ MK[1][1] ^ MK[1][2]
                                keyVec[1][0] = MK[0][0] ^ MK[0][1] ^ MK[0][2] ^ MK[3][1]
                                keyVec[1][1] = MK[1][0] ^ MK[1][1] ^ MK[1][3] ^ MK[3][2] ^ 1
                                U1 = keyVec ^ vec1
                                U2 = keyVec ^ vec2
                                inNum11 = 8 * U1[0][0] + 4 * U1[0][1] + 2 * U1[1][0] + U1[1][1]
                                inNum12 = 8 * U1[0][2] + 4 * U1[0][3] + 2 * U1[1][2] + U1[1][3]
                                inNum21 = 8 * U2[0][0] + 4 * U2[0][1] + 2 * U2[1][0] + U2[1][1]
                                inNum22 = 8 * U2[0][2] + 4 * U2[0][3] + 2 * U2[1][2] + U2[1][3]
                                num3 = 0
                                num4 = 1
                                outNum11 = RF_Op.SBOX(inNum11, num3)
                                outNum12 = RF_Op.SBOX(inNum12, num4)
                                outNum21 = RF_Op.SBOX(inNum21, num3)
                                outNum22 = RF_Op.SBOX(inNum22, num4)
                                B5 = Bsc.Int2Nib(outNum11)
                                T1[0][0] = B5[0]
                                T1[0][1] = B5[1]
                                T1[1][0] = B5[2]
                                T1[1][1] = B5[3]
                                B6 = Bsc.Int2Nib(outNum12)
                                T1[0][2] = B6[0]
                                T1[0][3] = B6[1]
                                T1[1][2] = B6[2]
                                T1[1][3] = B6[3]
                                B7 = Bsc.Int2Nib(outNum21)
                                T2[0][0] = B7[0]
                                T2[0][1] = B7[1]
                                T2[1][0] = B7[2]
                                T2[1][1] = B7[3]
                                B8 = Bsc.Int2Nib(outNum22)
                                T2[0][2] = B8[0]
                                T2[0][3] = B8[1]
                                T2[1][2] = B8[2]
                                T2[1][3] = B8[3]
                                deltaT = T1 ^ T2
                                w1 = sum(deltaT[0, :])
                                w2 = sum(deltaT[1, :])
                                if (w1 == 3 and w2 == 0) or  (w1 == 0 and w2 == 3):
                                    num5 = 8 * MK[0][0] + 4 * MK[0][1] + 2 * MK[0][2] + MK[0][3]
                                    num6 = 8 * MK[1][0] + 4 * MK[1][1] + 2 * MK[1][2] + MK[1][3]
                                    num7 = 8 * MK[2][0] + 4 * MK[2][1] + 2 * MK[2][2] + MK[2][3]
                                    num8 = 8 * MK[3][0] + 4 * MK[3][1] + 2 * MK[3][2] + MK[3][3]
                                    discardIndex = int(num5) * 4096 + int(num6) * 256 + int(num7) * 16 + int(num8)
                                    keyList[discardIndex] = False
                    flag = True
                    y = round(100 * i / Len, 3)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"ADTM: {y}% of the partial decryption has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            return keyList

    except ValueError as e:
        print("Error: Invalid inputs.", e)

###################################################################################################
####                                    Brute Force                                     ####
###################################################################################################
def ADTM_Search(ctx1: np.uint8, ctx2: np.uint8, keyList: list) -> None:
    try:
        m1, n1 = ctx1.shape
        m2, n2 = ctx1.shape
        if ctx1.dtype != np.uint8 or m1 != 4 or n1 != 4 or m2 != 4 or n2 != 4 or type(keyList) != list:
            raise TypeError("The first and the second inputs must be binary 4x4 matrices and the last input must be a list of boolean variables.")
        else:
            for i in range(0, 65536):
                if type(keyList[i]) != bool:
                    raise ValueError("The last input must be a list of boolean variables.")
                else:
                    MK = np.array([[0, 0, 0, 0],
                                   [0, 0, 0, 0],
                                   [0, 0, 0, 0],
                                   [0, 0, 0, 0]], dtype = np.uint8)
                    ptx1 = np.array([[0, 0, 0, 0],
                                     [0, 0, 0, 0],
                                     [0, 0, 0, 0],
                                     [0, 0, 0, 0]], dtype = np.uint8)
                    ptx2 = np.array([[0, 0, 0, 0],
                                     [0, 0, 0, 0],
                                     [0, 0, 0, 0],
                                     [0, 1, 0, 0]], dtype = np.uint8)
                    if keyList[i] == False:
                        continue
                    else:
                        num1 = i % 16
                        temp = (i - num1) // 16
                        num2 = temp % 16
                        temp = (temp - num2) // 16
                        num3 = temp % 16
                        temp = (temp - num3) // 16
                        num4 = temp
                        B1 = Bsc.Int2Nib(np.uint8(num4))
                        B2 = Bsc.Int2Nib(np.uint8(num3))
                        B3 = Bsc.Int2Nib(np.uint8(num2))
                        B4 = Bsc.Int2Nib(np.uint8(num1))
                        MK[0, :] = B1.copy()
                        MK[1, :] = B2.copy()
                        MK[2, :] = B3.copy()
                        MK[3, :] = B4.copy()
                        cHat1 = Enc.Enc(ptx1, MK, 7)
                        deltaC = ctx1 ^ cHat1
                        w = np.sum(deltaC)
                        if w == 0:
                            cHat2 = Enc.Enc(ptx2, MK, 7)
                            deltaC2 = ctx2 ^ cHat2
                            w2 = np.sum(deltaC2)
                            if w2 == 0:
                                hexList = "0123456789abcdef"
                                keyString = "0x"
                                keyString += hexList[num4] 
                                keyString += hexList[num3]
                                keyString += hexList[num2]
                                keyString += hexList[num1]
                                print(f"Masterkey has been recovered. Key is: {keyString}")
                                break
                            else:
                                continue
                flag = True
                y = round(100 * i / 65536, 3)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"ADTM: {y}% of the final search has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue
    except TypeError as e1:
        print("Error: Invalid inputs.", e1)

    except ValueError as e2:
        print("Error: Invalid inputs.", e2)


