import numpy as np
import Basic as Bsc
import RF_Operators as RF_Op
from math import log, ceil

"""
Instruction:
  DDTM.py - prepares plaintext sets; computes counts of plaintexts required for a target success probability and writes them in a text file.
  Also, it reads the ciphertexts generated by CDTM, compute the counts of ciphertexts and make a decision about the generator of it.
"""

###################################################################################################
####                     Writing the required plaintexts into a text file                      ####
###################################################################################################
def WriteDoc(ptxList: list, Address: str) -> None:
    try:
        if type(ptxList) != list:
            raise TypeError("The first input must be a list of plaintexts.")
        else:
            Address = Address + "\\Plaintexts.txt"
            Len = len(ptxList)
            flag = True
            with open(Address, "w") as f:
                for i in range(0, Len):
                    f.write("0x")
                    for j in range(0, 4):
                        num = 8 * ptxList[i][j][0] + 4 * ptxList[i][j][1] + 2 * ptxList[i][j][2] + ptxList[i][j][3]
                        f.write(Bsc.Int2Hex(num))
                    f.write("\n")
                    y = round((i + 1) / Len * 100, 2)
                    if abs(y - round(y)) < 0.05 and flag == True:
                        print(f"DDTM: {round(y)}% of the writing has been completed.")
                        flag = False
                    elif abs(y - round(y)) >= 0.05:
                        flag = True
                    else:
                        continue
            f.close()

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                    Reading blocks from the text file prepared by CDTM                     ####
###################################################################################################
def ReadDoc(Address: str) -> list:
    try:
        if type(Address) != str:
            raise TypeError("Input must be the address of the target file.")
        else:
            ctxList = []
            Address = Address + "\\Ciphertexts.txt"
            with open(Address, "r") as f:
                Data = f.read()
                f.close()
            Len = len(Data)
            ctr = 0
            ctr2 = 0
            flag = True
            while(ctr < Len):
                if Data[ctr] == "0" and Data[ctr + 1] == "x":
                    ctr += 2
                elif Data[ctr - 2] == "0" and Data[ctr - 1] == "x":
                    ctr3 = 0
                    X = np.array([
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0],
                        [0, 0, 0, 0]
                        ], dtype = np.uint8)
                    for i in range(0, 4):
                        num = Bsc.Hex2Int(Data[ctr + ctr3])
                        B = Bsc.Int2Nib(num)
                        X[i, :] = B.copy()
                        ctr3 += 1
                    ctr += 4
                    ctxList.append(X.copy())
                elif Data[ctr] == "\n":
                    ctr += 1
                    ctr2 += 1
                else:
                    ctr += 1
                y = round(100 * ctr / Len, 2)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"DDTM: {round(y)}% of the reading has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue
            return ctxList

    except TypeError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####                       Preparing and writing the required plaintexts                       ####
###################################################################################################
def DDTM_Generate(pr: float, Address: str) -> None:
    try:
        if type(pr) != float or pr < 0.5 or pr > 1:
            raise ValueError("The input must be a float between 0.5 and 1.")
        else:
            M = ceil(1024 / 15 * log(1 / (1 - pr)))
            if M > 4096:
                M = 4096
            print(f"The number of plaintexts pairs required to achieve a success probability of {pr} is: {M}.")
            ptxList = []
            randomList = Bsc.RndList(4096, M)
            for i in range(0, M):
                randomVector = Bsc.RndVector(randomList[i])
                X = np.array([
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0]
                    ], dtype = np.uint8)
                Y = np.array([
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0],
                    [0, 0, 0, 0]
                    ], dtype = np.uint8)
                for j in range (0, 4):
                    X[j, :] = Bsc.Int2Nib(randomVector[j])
                Y = X.copy()
                for j in range(0, 15):
                    binVec = Bsc.Int2Nib(np.uint8(j))
                    X[0][0] = binVec[0]
                    X[0][1] = binVec[1]
                    X[1][0] = binVec[2]
                    X[1][1] = binVec[3]
                    for l in range(j + 1, 16):
                        binVec = Bsc.Int2Nib(np.uint8(l))
                        Y[0][0] = binVec[0]
                        Y[0][1] = binVec[1]
                        Y[1][0] = binVec[2]
                        Y[1][1] = binVec[3]
                        ptxList.append(X.copy())
                        ptxList.append(Y.copy())
                flag = True
                y = round(100 * i / M, 2)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"DDTM: {round(y)}% of the generating plaintext pairs has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue 
            WriteDoc(ptxList, Address)

    except ValueError as e:
        print("Error: Invalid input.", e)

###################################################################################################
####        Processing the received data and making decision about the generator of it         ####
###################################################################################################
def DDTM_Decision(Address: str) -> bool:
    try:
        if type(Address) != str:
            raise TypeError("The first input must be a valid address.")
        else:
            listData = ReadDoc(Address)
            N = len(listData)
            M = N // 2
            ctr = 0
            flag = True
            bHat = False
            ctr2 = 0
            for i in range(0, M):
                X = listData[2 * i]
                Y = listData[2 * i + 1]
                Z = RF_Op.Sigma(X, Y)
                W = np.array([[0, 0, 0, 0],
                              [0, 0, 0, 0]], dtype = np.uint8)
                V = np.array([[0, 0, 0, 0],
                              [0, 0, 0, 0]], dtype = np.uint8)
                V[0, :] = Z[0, :].copy()
                V[1, :] = Z[1, :].copy()
                sumV = np.sum(V)
                W[0, :] = Z[2, :].copy()
                W[1, :] = Z[3, :].copy()
                sumW = np.sum(W)
                if sumW == 1 and sumV == 0:
                    bHat = True
                    ctr2 += 1
                ctr += 1
                y = round(100 * ctr / (N * 65536), 2)
                if abs(y - round(y)) < 0.05 and flag == True:
                    print(f"DDTM: {round(y)}% of the processing has been completed.")
                    flag = False
                elif abs(y - round(y)) >= 0.05:
                    flag = True
                else:
                    continue
            if bHat == True:
                print(f"\n\n\nNumber of impossible-differential satisfactions: {ctr2}\nDDTM found {ctr2} differentials, satisfying the impossible-differential proprty.\n******DDTM has decided that output blocks are generated by a random oracle.******\n\n\n")
            else:
                print(f"\n\n\nNumber of impossible-differential satisfactions: {ctr2}\nDDTM did not find any differentials, satisfying the impossible-differential property.\n******DDTM has decided that output blocks are picoCrypton ciphertexts.******\n\n\n")
            return bHat

    except TypeError as e:
        print("Error: Invalid input.", e)